#override defaults for dev
version: "3.7"

services:
  app_server:
    image: shopware-production:local
    build: .
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/app
      - APP_URL=http://localhost:8080
      - APP_SECRET=
      - INSTANCE_ID=
      - APP_ENV=prod
      - SHOPWARE_HTTP_CACHE_ENABLED=1
      - SHOPWARE_HTTP_DEFAULT_TTL=7200
      - SHOPWARE_CDN_STRATEGY_DEFAULT=INSTANCE_ID
      - BLUE_GREEN_DEPLOYMENT=1
      - MAILER_URL=null
      #- TRUSTED_PROXIES=127.0.0.1
    ports:
      - 8080:8000
    volumes:
      - "./config/jwt:/var/www/html/config/jwt"
      - "./public/media:/var/www/html/public/media"
      - "./public/thumbnail:/var/www/html/public/thumbnail"
      - "./public/bundles:/var/www/html/public/bundles"
      - "./files:/var/www/html/files"
      - "./custom:/var/www/html/custom"

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
